ArgocdApplications:

  #=================================#
  #      Platform Core Apps         #
  #=================================#

  argocd-image-updater:
    enabled: false

  raw:
    enabled: true

  vcluster:
    enabled: false

  #=================================#
  #          Data Services          #
  #=================================#

  database:
    enabled: true

  postgres-operator:
    enabled: true

  pgadmin:
    enabled: false

  redis:
    enabled: false

  minio:
    enabled: false

  object-storage:
    enabled: false

  #=================================#
  #      Network Services           #
  #=================================#

  metallb:
    enabled: true
    ignoreDifferences:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        name: bgppeers.metallb.io
        jsonPointers:
          - /spec/conversion/webhook/clientConfig/caBundle

  external-dns:
    enabled: true

  ingress-nginx-internal:
    enabled: true

  ingress-nginx-external:
    enabled: true

  cilium:
    enabled: true
    syncWave: 1
    ignoreDifferences:
      - group: "*"
        kind: "*"
        jsonPointers:
        - /spec/template/spec/securityContext/appArmorProfile
  #=================================#
  #      Security & Auth            #
  #=================================#

  cert-manager:
    enabled: true

  oauth2-proxy:
    enabled: true
    syncWave: 2

  kyverno:
    enabled: false

  policy:
    enabled: false

  vault:
    enabled: false

  vault-secrets-operator:
    enabled: false
    namespace: vault

  secrets:
    enabled: false

  #=================================#
  #      Monitoring Stack           #
  #=================================#

  metrics-server:
    enabled: true
    syncWave: 1

  promtail:
    enabled: true
    syncWave: 2

  opencost:
    enabled: true
    syncWave: 1

  #=================================#
  #      Example Applications       #
  #=================================#

  grpc-server:
    enabled: false

  show-env:
    enabled: true
    annotations:
      argocd-image-updater.argoproj.io/image-list: ghcr.io/kuberise/show-env:latest
      argocd-image-updater.argoproj.io/update-strategy: digest
      argocd-image-updater.argoproj.io/write-back-method: git

  frontend-https:
    enabled: true
    syncWave: 1

  backend:
    enabled: true
