# Default values for kyverno
kyverno:
  admissionController:
    serviceMonitor:
      enabled: true
  backgroundController:
    serviceMonitor:
      enabled: true
  cleanupController:
    serviceMonitor:
      enabled: true
  reportsController:
    serviceMonitor:
      enabled: true
