metrics-server:
  metrics:
    enabled: true

  serviceMonitor:
    enabled: true
    interval: 1m
    scrapeTimeout: 10s

  defaultArgs:
    - --cert-dir=/tmp
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --kubelet-use-node-status-port
    - --metric-resolution=15s
    - --kubelet-insecure-tls
