opencost:
  opencost:
    prometheus:
      internal:
        enabled: false
      external:
        enabled: true
        url: http://kube-prometheus-stack-prometheus.monitoring:9090
      amp:
        enabled: false
    ui:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: nginx-external
        # annotations:
          # nginx.ingress.kubernetes.io/auth-url: https://oauth2-proxy.{{ .Values.global.domain }}/oauth2/auth
          # nginx.ingress.kubernetes.io/auth-signin: https://oauth2-proxy.{{ .Values.global.domain }}/oauth2/start
        hosts: [] # set this in the platform specific values file because opencost doesn't support tpl for this


    metrics:
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
