ingress-nginx:
  controller:
    hostPort:
      enabled: true

    updateStrategy:
      type: Recreate
      # because in RollingUpdate for any changes, kubernetes will create a new pod and then delete the old one.
      # But the new pod and the old pod will conflict on the same port number. So, we need to use Recreate strategy.
      # This means that if you change configuration of external nginx controller, you will have few seconds of down time.

    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "*.{{ .Values.global.domain }}"
        external-dns.alpha.kubernetes.io/owner: "onprem-externaldns"
      nodePorts: # This is the port that will be used to access the service from outside the cluster. We map this port from minikube or kind container to 80 and 443 on the host machine.
        http: 30080
        https: 30443

    extraArgs:
      default-ssl-certificate: cert-manager/ssl-certificate-selfsigned

    terminationGracePeriodSeconds: 5 # only for dev environment and local/onprem
